[build]
base = ".netlify"
publish = ".netlify/build"
command = "make"

# Permanent redirect from the netlify domain to the canonical domain
[[redirects]]
from = "https://org-pietroalbini-botogram.netlify.com/*"
to = "https://botogram.pietroalbini.org/:splat"
status = 301
force = true

# Redirect to the latest docs
[[redirects]]
from = "/docs/"
to = "/docs/0.5/"
status = 302

# Security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Xss-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"

